insert into `tbl_outbound_temp` 
SELECT `tbl_outbound_missing`.`osh_id`,
    `tbl_outbound_missing`.`osh_sender_number`,
    `tbl_outbound_missing`.`osh_receiver_number`,
    `tbl_outbound_missing`.`osh_via`,
    `tbl_outbound_missing`.`osh_user_id`,
    `tbl_outbound_missing`.`osh_campaign_id`,
    `tbl_outbound_missing`.`osh_smpp_messageid`,
    `tbl_outbound_missing`.`osh_message`,
    `tbl_outbound_missing`.`osh_sms_count`,
    `tbl_outbound_missing`.`osh_sms_status`,
    `tbl_outbound_missing`.`osh_status_code`,
    `tbl_outbound_missing`.`osh_universal_sms_count`,
    `tbl_outbound_missing`.`osh_time`,
    `tbl_outbound_missing`.`osh_response_time`,
    `tbl_outbound_missing`.`osh_message_type`,
    `tbl_outbound_missing`.`osh_delivery_time`,
    `tbl_outbound_missing`.`osh_jasmin_response`,
    `tbl_outbound_missing`.`osh_country`,
    `tbl_outbound_missing`.`osh_dlr_notification_url`,
    `tbl_outbound_missing`.`osh_customer_msg_id`,
    `tbl_outbound_missing`.`osh_dlr_notifiation_method`,
    `tbl_outbound_missing`.`osh_dlr_error`,
    `tbl_outbound_missing`.`osh_date`,
    `tbl_outbound_missing`.`oshOriginalID`,
    `tbl_outbound_missing`.`osh_join_column`,
    `tbl_outbound_missing`.`osh_api_id`,
    `tbl_outbound_missing`.`osh_msc`,
    `tbl_outbound_missing`.`osh_provider`,
    `tbl_outbound_missing`.`osh_im_id`,
    `tbl_outbound_missing`.`imsi`
FROM `multi_send_rmq`.`tbl_outbound_missing`
where osh_time between '2019-04-01 00:00:00' and 2019-04-01 23:59:59;
